back/api/urls.py
from django.urls import path

from . import views
from . import ai_views
from . import pdf_views

app_name = "api"
urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("employees/", views.EmployeeView.as_view(), name="employees"),
    path("sequences/", views.SequenceView.as_view(), name="sequences"),
    path("ai-content-generate/", ai_views.generate_ai_content, name="ai-content-generate"),
    path("pdf-extract-questions/", pdf_views.extract_questions_from_pdf, name="pdf-extract-questions"),
]

back/back/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from admin.admin_tasks import urls as admin_tasks_urls
from admin.appointments import urls as appointment_urls
from admin.badges import urls as badge_urls
from admin.hardware import urls as hardware_urls
from admin.integrations import urls as integrations_urls
from admin.introductions import urls as intro_urls
from admin.people import urls as people_urls
from admin.preboarding import urls as preboarding_urls
from admin.resources import urls as resource_urls
from admin.sequences import urls as sequences_urls
from admin.settings import urls as settings_urls
from admin.templates import urls as template_urls
from admin.to_do import urls as to_do_urls
from ai_assistant import urls as ai_assistant_urls
from api import urls as public_api_urls
from new_hire import urls as new_hire_urls
from organization import urls as org_urls
from organization import views as org_views
from slack_bot import urls as slack_urls
from users import urls as auth_urls

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include(auth_urls)),
    path("api/org/", include(org_urls)),
    path("setup/", org_views.InitialSetupView.as_view(), name="setup"),
    path("admin/people/", include((people_urls, "admin.people"), namespace="admin")),
    path("admin/settings/", include(settings_urls)),
    path("admin/tasks/", include(admin_tasks_urls)),
    path("admin/templates/", include(template_urls)),
    path("admin/templates/todo/", include(to_do_urls)),
    path("admin/templates/hardware/", include(hardware_urls)),
    path("admin/templates/introductions/", include(intro_urls)),
    path("admin/templates/resources/", include(resource_urls)),
    path("admin/templates/badges/", include(badge_urls)),
    path("admin/templates/preboarding/", include(preboarding_urls)),
    path("admin/templates/appointments/", include(appointment_urls)),
    path("new_hire/", include(new_hire_urls)),
    path("admin/sequences/", include(sequences_urls)),
    path("api/slack/", include(slack_urls)),
    path("admin/integrations/", include(integrations_urls)),
    path("admin/ai-assistant/", include(ai_assistant_urls)),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

# API
if settings.API_ACCESS:
    urlpatterns += [
        path("api/", include(public_api_urls)),
    ]

# DJANGO DEBUG BAR
if settings.DEBUG and not settings.RUNNING_TESTS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

back/new_hire/urls.py
from django.urls import path

from new_hire import views

app_name = "new_hire"
urlpatterns = [
    path("todos/", views.NewHireDashboard.as_view(), name="todos"),
    path("resources/", views.ResourceListView.as_view(), name="resources"),
    path(
        "resources/search/",
        views.ResourceSearchView.as_view(),
        name="resources-search",
    ),
    path(
        "resources/<int:pk>/<int:chapter>/",
        views.ResourceDetailView.as_view(),
        name="resource-detail",
    ),
    path(
        "resources/form/<int:pk>/<int:chapter>/",
        views.CourseAnswerView.as_view(),
        name="question-form",
    ),
    path(
        "course/<int:pk>/", views.CourseNextStepView.as_view(), name="course-next-step"
    ),
    path("todos/<int:pk>/", views.ToDoDetailView.as_view(), name="to_do"),
    path("slackform/<int:pk>/", views.SlackToDoFormView.as_view(), name="slack_to_do"),
    path(
        "todos/<int:pk>/complete/",
        views.ToDoCompleteView.as_view(),
        name="to_do_complete",
    ),
    path(
        "<int:pk>/form/<slug:type>/",
        views.FormSubmitView.as_view(),
        name="form",
    ),
    path("colleagues/", views.ColleagueListView.as_view(), name="colleagues"),
    path(
        "colleagues/search/",
        views.ColleagueSearchView.as_view(),
        name="colleagues-search",
    ),
    path(
        "preboarding/",
        views.PreboardingShortURLRedirectView.as_view(),
        name="preboarding-url",
    ),
    path(
        "preboarding/<int:pk>/",
        views.PreboardingDetailView.as_view(),
        name="preboarding",
    ),
    path(
        "updates/",
        views.SeenUpdatesView.as_view(),
        name="seen-updates",
    ),
]

back/admin/people/views/new_hires.py
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone, translation
from django.utils.translation import gettext as _
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView
from django.views.generic.list import ListView
from django_q.tasks import async_task
from twilio.rest import Client

from admin.admin_tasks.models import AdminTask
from admin.admin_tasks.selectors import get_admin_tasks_for_user
from admin.integrations.forms import IntegrationExtraUserInfoForm
from admin.notes.models import Note
from admin.people.forms import (
    NewHireAddForm,
    NewHireProfileForm,
    OnboardingSequenceChoiceForm,
    PreboardingSendForm,
    RemindMessageForm,
)
from admin.people.selectors import get_colleagues_for_user, get_new_hires_for_user
from admin.sequences.models import Condition, Sequence
from admin.sequences.selectors import get_sequences_for_user
from admin.templates.utils import get_templates_model, get_user_field
from misc.mixins import FormWithUserContextMixin
from organization.models import Notification, Organization, WelcomeMessage
from slack_bot.slack_resource import SlackResource
from slack_bot.slack_to_do import SlackToDo
from slack_bot.tasks import link_slack_users
from slack_bot.utils import Slack, paragraph
from users.emails import (
    email_reopen_task,
    send_new_hire_credentials,
    send_new_hire_preboarding,
    send_reminder_email,
)
from users.mixins import AdminOrManagerPermMixin
from users.models import (
    NewHireWelcomeMessage,
    PreboardingUser,
    ResourceUser,
    ToDoUser,
    UserCondition,
)


class NewHireListView(AdminOrManagerPermMixin, ListView):
    template_name = "new_hires.html"
    paginate_by = settings.NEW_HIRE_PAGINATE_BY

    def get_queryset(self):
        return get_new_hires_for_user(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("New hires")
        context["subtitle"] = _("people")
        context["add_action"] = reverse_lazy("people:new_hire_add")
        return context


class NewHireAddView(AdminOrManagerPermMixin, SuccessMessageMixin, CreateView):
    template_name = "new_hire_add.html"
    model = get_user_model()
    form_class = NewHireAddForm
    success_message = _("New hire has been created")
    success_url = reverse_lazy("people:new_hires")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Add new hire")
        context["subtitle"] = _("people")
        return context

    def form_valid(self, form):
        sequences = form.cleaned_data.pop("sequences")

        # Set new hire role
        form.instance.role = get_user_model().Role.NEWHIRE

        new_hire = form.save()

        # additional sequences, then add the ones from the roles
        sequence_pks = list(sequences.values_list("pk", flat=True))

        for role in form.cleaned_data["roles"]:
            role.users.add(new_hire)
            sequence_pks += list(
                role.sequences.all().values_list("pk", flat=True)
            ) + list(role.department.sequences.all().values_list("pk", flat=True))

        sequences = Sequence.objects.filter(id__in=sequence_pks)
        new_hire.add_sequences(Sequence.objects.filter(id__in=sequence_pks))

        # Send credentials email if the user was created after their start day
        org = Organization.object.get()
        new_hire_datetime = new_hire.get_local_time()
        if (
            new_hire_datetime.date() >= new_hire.start_day
            and new_hire_datetime.hour >= 7
            and new_hire_datetime.weekday() < 5
            and org.new_hire_email
        ):
            async_task(
                "users.tasks.send_new_hire_credentials",
                new_hire.id,
                task_name=f"Send login credentials: {new_hire.full_name}",
            )

        # Linking user in Slack and sending welcome message (if exists)
        link_slack_users([new_hire])

        Notification.objects.create(
            notification_type=Notification.Type.ADDED_NEWHIRE,
            extra_text=new_hire.full_name,
            created_by=self.request.user,
            created_for=new_hire,
        )

        # Update user amount completed
        new_hire.update_progress()

        # Check if there are items that will not be triggered since date passed
        conditions = Condition.objects.none()
        for seq in sequences:
            if new_hire.workday() == 0:
                # User has not started yet, so we only need the items before they new
                # hire started that passed
                conditions |= seq.conditions.filter(
                    condition_type=Condition.Type.BEFORE,
                    days__gte=new_hire.days_before_starting(),
                )
            else:
                # user has already started, check both before start day and after for
                # conditions that are not triggered
                conditions |= seq.conditions.filter(
                    condition_type=Condition.Type.BEFORE
                ) | seq.conditions.filter(
                    condition_type=Condition.Type.AFTER, days__lte=new_hire.workday()
                )

        if conditions.count():
            return render(
                self.request,
                "not_triggered_conditions.html",
                {
                    "conditions": conditions,
                    "title": new_hire.full_name,
                    "subtitle": "new hire",
                    "employee": new_hire,
                },
            )

        return super().form_valid(form)


class NewHireSendPreboardingNotificationView(AdminOrManagerPermMixin, FormView):
    template_name = "trigger_preboarding_notification.html"
    form_class = PreboardingSendForm

    def form_valid(self, form):
        new_hire = get_object_or_404(
            get_new_hires_for_user(user=self.request.user), id=self.kwargs.get("pk", -1)
        )
        if form.cleaned_data["send_type"] == "email":
            send_new_hire_preboarding(new_hire, form.cleaned_data["email"])
        else:
            client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
            client.messages.create(
                to=new_hire.phone,
                from_=settings.TWILIO_FROM_NUMBER,
                body=new_hire.personalize(
                    WelcomeMessage.objects.get(
                        language=new_hire.language,
                        message_type=WelcomeMessage.Type.TEXT_WELCOME,
                    ).message
                ),
            )
        return redirect("people:new_hire", pk=new_hire.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get("pk", -1)
        new_hire = get_object_or_404(
            get_new_hires_for_user(user=self.request.user), id=user_id
        )
        context["title"] = new_hire.full_name
        context["subtitle"] = "new hire"
        return context


class NewHireAddSequenceView(
    AdminOrManagerPermMixin, FormWithUserContextMixin, FormView
):
    template_name = "new_hire_add_sequence.html"
    form_class = OnboardingSequenceChoiceForm

    def form_valid(self, form):
        user_id = self.kwargs.get("pk", -1)
        new_hire = get_object_or_404(
            get_new_hires_for_user(user=self.request.user), id=user_id
        )
        sequences = Sequence.objects.filter(id__in=form.cleaned_data["sequences"])
        new_hire.add_sequences(sequences, new_hire.get_local_time().date())
        messages.success(
            self.request, _("Sequence(s) have been added to this new hire")
        )

        # Check if there are items that will not be triggered since date passed
        conditions = Condition.objects.none()
        for seq in sequences:
            if new_hire.workday() == 0:
                # User has not started yet, so we only need the items before they new
                # hire started that passed
                conditions |= seq.conditions.filter(
                    condition_type=Condition.Type.BEFORE,
                    days__gte=new_hire.days_before_starting(),
                )
            else:
                # user has already started, check both before start day and after for
                # conditions that are not triggered
                conditions |= seq.conditions.filter(
                    condition_type=Condition.Type.BEFORE
                ) | seq.conditions.filter(
                    condition_type=Condition.Type.AFTER, days__lte=new_hire.workday()
                )

        if conditions.count():
            # Prefetch records to avoid a massive amount of queries
            conditions = Condition.objects.prefetched().filter(
                id__in=conditions.values_list("pk", flat=True)
            )
            return render(
                self.request,
                "not_triggered_conditions.html",
                {
                    "conditions": conditions,
                    "title": new_hire.full_name,
                    "subtitle": "new hire",
                    "employee": new_hire,
                },
            )
        return redirect("people:new_hire", pk=new_hire.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

back/new_hire/templates/_chapter_recursive.html
<div style="margin-left:{{extra_margin}}px;">
{% if sub_chapter_item.children|length > 0 %}
  <div class="list-group-header sticky-top">{{ sub_chapter_item.name }}</div>
  {% for item in sub_chapter_item.children %}
    {% include '_chapter_recursive.html' with sub_chapter_item=item extra_margin=10 %}
  {% endfor %}
{% else %}
  {% if not object.course and sub_chapter_item.type == 2 %}
    {# not a course, so don't show #}
  {% elif object.course and sub_chapter_item.type == 2 and resource_user.completed_course %}
    {# a course, but completed, so don't show #}
  {% else %}
  <div class="list-group-item" style="border-left: 0px none; ">
    <div class="row align-items-center">
      <div class="col-auto">
        <span class="badge {% if view.kwargs.chapter == sub_chapter_item.id %}bg-primary{% endif %}"></span>
      </div>
      <div class="col text-truncate">
        {% if object.course and resource_user.step < sub_chapter_item.order and not resource_step.completed_course %}
          <s><span class="text-body d-block">{{ sub_chapter_item.name }}</span></s>
        {% else %}
          <a href="{% url 'new_hire:resource-detail' object.id sub_chapter_item.id %}" class="text-body d-block">{{ sub_chapter_item.name }}</a>
        {% endif %}
    </span>
      </div>
    </div>
  </div>
  {% endif %}
{% endif %}
</div>

back/new_hire/templates/_question_form.html
{% load crispy_forms_tags %}
{% load i18n %}
<form method="post" hx-post="{% url 'new_hire:question-form' object.pk chapter.pk %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">{% translate "Submit" %}</button>
</form>

back/new_hire/templates/new_hire_base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>{% translate "Employee onboarding" %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    <!-- CSS files -->
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/extra.css' %}">
    <style>
      .btn-primary, .btn-outline-primary, .btn-ghost-primary, .btn-primary:hover, .btn-outline-primary:hover, .btn-ghost-primary:hover, .border-primary, .navbar {
        --tblr-primary: rgb({{ org.base_color_rgb }});
        --tblr-btn-hover-bg: rgb({{ org.base_color_rgb }});
        --tblr-primary-rgb: {{ org.base_color_rgb }};
        --tblr-primary-darker: rgb({{ org.base_color_rgb }});
      }
      a, a:hover, a:focus {
        color: rgb({{ org.base_color_rgb }})
      }
      .form-control:focus {
        color: inherit;
        background-color: #ffffff;
        border-color: rgb({{ org.base_color_rgb }});
        outline: 0;
        box-shadow: 0 0 0 0.25rem rgba({{ org.base_color_rgb }}, 0.25);
      }
      .page-item.active .page-link {
        background-color: rgb({{ org.base_color_rgb }});
        border-color: rgb({{ org.base_color_rgb }});
      }
      .page-link:hover {
        color: rgb({{ org.base_color_rgb }});
      }
      .form-check-input:checked, .bg-primary  {
        background-color: rgb({{ org.base_color_rgb }}) !important;
      }
    </style>
  </head>
  <body class="">
    <div class="wrapper">
      {% block header %}
      <header class="navbar navbar-expand-md navbar-dark navbar-overlap d-print-none" style="background-color: {{ org.base_color }}">
        <div class="container-xl">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if org.get_logo_url != "" %}
          <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href=".">
              <img src="{{ org.get_logo_url }}" class="navbar-brand-image" width="110" height="32">
            </a>
          </h1>
          {% endif %}
          <div class="navbar-nav flex-row order-md-last">
            <div class="nav-item dropdown d-none d-md-flex me-3" onclick="updateSeen()">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-templates" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" /><path d="M9 17v1a3 3 0 0 0 6 0v-1" /></svg>
                  {% if request.user.has_new_hire_notifications %}
                    <span class="badge bg-red"></span>
                  {% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-card dropdown-menu-right" style="width: 30rem;">
                  <div class="card d-flex flex-column">
                    <div class="card-body d-flex flex-column">
                      <h3 class="card-title">Notifications</h3>
                      <div class="list-group list-group-flush list-group-hoverable">
                        {% for notification in request.user.notification_receivers.all %}
                          {% if notification.public_to_new_hire %}
                          <div class="list-group-item">
                            <div class="row align-items-center">
                              {% if notification.has_not_seen %}
                                <div class="col-auto"><span class="badge bg-primary"></span></div>
                              {% endif %}
                              <div class="col text-truncate">
                                {% if notification.full_link == "" %}
                                <p class="text-reset d-block mb-0">{{ notification.get_notification_type_display }}:<br> <strong>{{ notification.extra_text }}</strong></p>
                                {% else %}
                                  <a href="{{ notification.full_link }}" class="text-reset d-block mb-0">{{ notification.get_notification_type_display }}: {{ notification.extra_text }}</a>
                                {% endif %}
                              </div>
                            </div>
                          </div>
                          {% endif %}
                        {% empty %}
                          No notifications yet
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="nav-item dropdown">
              <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
                {% include "_profile_image.html" with user=request.user %}
                <div class="d-none d-xl-block ps-2">
                  <div>{{ user.full_name }}</div>
                  <div class="mt-1 small text-muted">{{ user.get_role_display }}</div>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  <button class="dropdown-item">{% translate "Logout" %}</button>
                </form>
              </div>
            </div>
          </div>
          <div class="collapse navbar-collapse" id="navbar-menu">
            <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
              {% if 'preboarding' not in request.path %}
              <ul class="navbar-nav">
                {% if request.user.role == 0 %}
                <li class="nav-item {% if 'todos' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:todos' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-circle-check" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <circle cx="12" cy="12" r="9"></circle>
                        <path d="M9 12l2 2l4 -4"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "To do items" %}
                    </span>
                  </a>
                </li>
                {% endif %}
                <li class="nav-item {% if 'resources' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:resources' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-folders" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M9 4h3l2 2h5a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2"></path>
                        <path d="M17 17v2a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2h2"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "Resources" %}
                    </span>
                  </a>
                </li>
                <li class="nav-item {% if 'colleagues' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:colleagues' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-users" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                        <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "Colleagues" %}
                    </span>
                  </a>
                </li>
              </ul>
              {% endif %}
            </div>
          </div>
        </div>
      </header>
      {% endblock %}
      <div class="page-wrapper">
        <div class="container-xl">
          <!-- Page title -->
          <div class="page-header text-white d-print-none">
            <div class="row align-items-center">
              <div class="col">
                <!-- Page pre-title -->
                <h2 class="page-title">{{ title }}</h2>
                <div class="page-pretitle">
                  {{ subtitle }}
                </div>
              </div>
              <!-- Page title actions -->
              {% for message in messages %}
              <div class="alert alert-success" style="color: black;">
                {{ message }}
              </div>
            {% endfor %}
              {% block actions %}
              {% endblock %}
            </div>
          </div>
        </div>
        <div class="page-body">
          <div class="container-xl">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>
      <div id="bin">
      </div>
    </div>
    <script src="{% static 'js/tabler.js' %}"></script>
    <script src="{% static 'js/htmx-2.0.8.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', function(event) {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
    <script>
      function updateSeen() {
          htmx.ajax("get", "{% url 'new_hire:seen-updates' %}", "#bin")
      }
    </script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

back/new_hire/templates/new_hire_resources.html
{% extends 'new_hire_base.html' %}
{% load i18n %}
{% load humanize %}

{% block actions %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{% translate "Resources" %}</h3>
      </div>
      <div class="list-group list-group-flush list-group-hoverable">
        {% for resource_user in object_list %}
          {% ifchanged resource_user.resource.category %}
            {% if resource_user.resource.category is not None %}
              <div class="list-group-header sticky-top">{{ resource_user.resource.category }}</div>
            {% endif %}
          {% endifchanged %}
        <div class="list-group-item" style="border-left: 0px none;">
          <div class="row align-items-center">
            <div class="col-auto">
              <span class="badge {% if resource_user.resource.course %} bg-primary {% endif %}"></span>
            </div>
            <div class="col text-truncate">
              <a href="{% url 'new_hire:resource-detail' resource_user.resource.id resource_user.resource.first_chapter_id %}" class="text-body d-block">{{ resource_user.resource.name }}</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{% translate "Search through resources" %}</h3>
      </div>
      <div class="card-body">
        <div class="input-icon float-right w-100">
          <input type="search"
                 class="form-control d-inline-block w-9 me-3"
                 placeholder="Search resources…"
                 name="search"
                 hx-get="{% url 'new_hire:resources-search' %}"
                 hx-trigger="keyup delay:500ms changed"
                 hx-target="#search-results"
                 hx-indicator="#spinner"
                 >
                 <span class="input-icon-addon requesting" id="spinner">
                   <div class="spinner-border spinner-border-sm text-muted" role="status"></div>
                 </span>
        </div>
        <div id="search-results"></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}